sudo: required
services:
  - docker

before_install:
  - docker build -t kevinljd/rse-web

script:
  - docker run kevinljd/rse-web


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact"
  bucket_name: "elasticbeanstalk-ap-southeast-2-571523081348"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"